-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 16:21:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database-qllk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database-qllk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database-qllk` DEFAULT CHARACTER SET utf8 ;
USE `database-qllk` ;

-- -----------------------------------------------------
-- Table `database-qllk`.`LOAIMATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`LOAIMATHANG` (
  `MaLoai` int NOT NULL AUTO_INCREMENT,
  `TenLoai` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaLoai`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`KHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`KHO` (
  `MaKhu` int NOT NULL AUTO_INCREMENT,
  `TenKhu` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaKhu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DONVITINH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DONVITINH` (
  `MaDV` int NOT NULL AUTO_INCREMENT,
  `TenDV` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaDV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`MATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`MATHANG` (
  `MaMH` int NOT NULL AUTO_INCREMENT,
  `TenMH` NVARCHAR(45) NOT NULL,
  `HangSX` NVARCHAR(45) NULL,
  `MaDV` int NULL,
  `CauHinh` NVARCHAR(100) NULL,
  `MaLoai` int NULL,
  `MaKhu` int NULL,
  `SoLuong` INT NULL,
  PRIMARY KEY (`MaMH`),
  INDEX `MaLoai_idx` (`MaLoai` ASC),
  INDEX `MaKhu_idx` (`MaKhu` ASC),
  INDEX `MaDV_idx` (`MaDV` ASC),
  CONSTRAINT `fk_MATHANG_LOAIMATHANG`
    FOREIGN KEY (`MaLoai`)
    REFERENCES `database-qllk`.`LOAIMATHANG` (`MaLoai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATHANG_KHO`
    FOREIGN KEY (`MaKhu`)
    REFERENCES `database-qllk`.`KHO` (`MaKhu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATHANG_DONVITINH`
    FOREIGN KEY (`MaDV`)
    REFERENCES `database-qllk`.`DONVITINH` (`MaDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHONGBAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHONGBAN` (
  `MaPhong` int NOT NULL AUTO_INCREMENT,
  `TenPhong` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaPhong`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`NHANVIEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`NHANVIEN` (
  `MaNV` int NOT NULL AUTO_INCREMENT,
  `TenNV` NVARCHAR(45) NOT NULL,
  `Phai` NVARCHAR(4) NULL,
  `MaPhong` int NULL,
  PRIMARY KEY (`MaNV`),
  INDEX `MaPhong_idx` (`MaPhong` ASC),
  CONSTRAINT `fk_NHANVIEN_PHONGBAN`
    FOREIGN KEY (`MaPhong`)
    REFERENCES `database-qllk`.`PHONGBAN` (`MaPhong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`KHACHHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`KHACHHANG` (
  `MaKH` int NOT NULL AUTO_INCREMENT,
  `TenKH` NVARCHAR(45) NOT NULL,
  `DiaChi` NVARCHAR(60) NULL,
  `Email` VARCHAR(40) NULL,
  `SoDT` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`HOADON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`HOADON` (
  `MaHD` int NOT NULL AUTO_INCREMENT,
  `NgayLap` DATETIME NULL,
  `MaSoThue` VARCHAR(45) NULL,
  `TongTien` INT NULL,
  `MaNV` int NULL,
  `MaKH` int NULL,  
  PRIMARY KEY (`MaHD`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaKH_idx` (`MaKH` ASC),
  CONSTRAINT `fk_HOADON_PNHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOADON_KHACHHANG`
    FOREIGN KEY (`MaKH`)
    REFERENCES `database-qllk`.`KHACHHANG` (`MaKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETHOADON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETHOADON` (
  `MaCTHD` int NOT NULL AUTO_INCREMENT,
  `DonGiaBan` INT NOT NULL,
  `SoLuong` INT NULL,
  `MaHD` int NULL,
  `MaMH` int NULL,
  `TienThanhToan` INT NOT NULL,
  PRIMARY KEY (`MaCTHD`),
  INDEX `MaHD_idx` (`MaHD` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETHOADON_HOADON`
    FOREIGN KEY (`MaHD`)
    REFERENCES `database-qllk`.`HOADON` (`MaHD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETHOADON_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`NHACUNGCAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`NHACUNGCAP` (
  `MaNCC` int NOT NULL AUTO_INCREMENT,
  `TenNCC` NVARCHAR(50) NULL,
  `DiaChiNCC` NVARCHAR(50) NULL,
  `EmailNCC` VARCHAR(40) NULL,
  `SoDTNCC` VARCHAR(15) NULL,
  PRIMARY KEY (`MaNCC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DONDATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DONDATHANG` (
  `MaDDH` int AUTO_INCREMENT NOT NULL,
  `NgayLap` DATETIME NULL,
  `MaNV` int NULL,
  `MaNCC` int NULL,
  PRIMARY KEY (`MaDDH`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaNCC_idx` (`MaNCC` ASC),
  CONSTRAINT `fk_DONDATHANG_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DONDATHANG_NHACUNGCAP`
    FOREIGN KEY (`MaNCC`)
    REFERENCES `database-qllk`.`NHACUNGCAP` (`MaNCC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETDONDATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETDONDATHANG` (
  `MaCTDDH` int NOT NULL AUTO_INCREMENT,
  `SoLuong` INT NULL,
  `MaDDH` int NULL,
  `MaMH` int NULL,
  PRIMARY KEY (`MaCTDDH`),
  INDEX `MaDDH_idx` (`MaDDH` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETDONDATHANG_DONDATHANG`
    FOREIGN KEY (`MaDDH`)
    REFERENCES `database-qllk`.`DONDATHANG` (`MaDDH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETDONDATHANG_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHANQUYEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHANQUYEN` (
  `MaPQ` int NOT NULL AUTO_INCREMENT,
  `TenPQ` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaPQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DANGNHAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DANGNHAP` (
  `MaDN` int NOT NULL AUTO_INCREMENT,
  `TenHienThi` NVARCHAR(30) NULL,
  `Username` VARCHAR(100) NULL,
  `Password` VARCHAR(20) NULL,
  `MaNV` int NULL,
  `MaPQ` int NULL,
  PRIMARY KEY (`MaDN`),
  INDEX `Username_idx` (`Username` ASC),
  INDEX `MaPQ_idx` (`MaPQ` ASC),
  CONSTRAINT `fk_DANGNHAP_PHANQUYEN`
    FOREIGN KEY (`MaPQ`)
    REFERENCES `database-qllk`.`PHANQUYEN` (`MaPQ`),
  CONSTRAINT `fk_DANGNHAP_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHIEUNHAPHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHIEUNHAPHANG` (
  `MaPN` int AUTO_INCREMENT NOT NULL,
  `NgayLapPhieu` DATETIME NULL,
  `MaNV` int NULL,
  `TongTienPN` INT NULL,
  `MaDDH` int NULL,
  PRIMARY KEY (`MaPN`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaDDH_idx` (`MaDDH` ASC),
  CONSTRAINT `fk_PHIEUNHAPHANG_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PHIEUNHAPHANG_DONDATHANG`
    FOREIGN KEY (`MaDDH`)
    REFERENCES `database-qllk`.`DONDATHANG` (`MaDDH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETPHIEUNHAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETPHIEUNHAP` (
  `MaCTPN` int AUTO_INCREMENT NOT NULL,
  `SoLuong` INT NULL,
  `DonGia` VARCHAR(45) NULL,
  `DonGiaBan` VARCHAR(45) NULL,
  `GhiChu` VARCHAR(45) NULL,
  `MaPN` int NULL,
  `TongTien` INT NULL,
  `MaMH` int NULL,
  PRIMARY KEY (`MaCTPN`),
  INDEX `MaPN_idx` (`MaPN` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETPHIEUNHAP_PHIEUNHAPHANG`
    FOREIGN KEY (`MaPN`)
    REFERENCES `database-qllk`.`PHIEUNHAPHANG` (`MaPN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETPHIEUNHAP_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`BAOCAOHANGTON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`BAOCAOHANGTON` (
  `MaBCHT` int AUTO_INCREMENT NOT NULL,
  `NgayLap` DATETIME NULL,
  `Thang` INT NULL,
  `TongNhap` INT NULL,
  `TongTon` INT NULL,
  `TongBan` INT NULL,
  `MaNV` int NULL,
  PRIMARY KEY (`MaBCHT`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  CONSTRAINT `fk_BAOCAOHANGTON_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`BAOCAOTHUCHI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`BAOCAOTHUCHI` (
  `MaBCTC` int AUTO_INCREMENT NOT NULL,
  `NgayLap` DATETIME NULL,
  `TongThu` INT NULL,
  `TongChi` INT NULL,
  `MaNV` int NULL,
  `TuyChon` VARCHAR(45) NULL,
  `ThoiGian` VARCHAR(8) NULL,
  PRIMARY KEY (`MaBCTC`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  CONSTRAINT `fk_BAOCAOTHUCHI_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETBAOCAOHANGTON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETBAOCAOHANGTON` (
  `MaCTBC` int AUTO_INCREMENT NOT NULL,
  `LuongNhapBĐ` INT NULL,
  `LuongBan` INT NULL,
  `LuongTon` INT NULL,
  `MaMH` int NULL,
  `MaBCHT` int NULL,
  PRIMARY KEY (`MaCTBC`),
  INDEX `MaMH_idx` (`MaMH` ASC),
  INDEX `MaBCHT_idx` (`MaBCHT` ASC),
  CONSTRAINT `fk_CHITIETBAOCAOHANGTON_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETBAOCAOHANGTON_BAOCAOHANGTON`
    FOREIGN KEY (`MaBCHT`)
    REFERENCES `database-qllk`.`BAOCAOHANGTON` (`MaBCHT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETTHU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETTHU` (
  `MaCTT` int AUTO_INCREMENT NOT NULL,
  `MaBCTC` int NULL,
  `MaMH` int NULL,
  `TongBan` INT NULL,
  PRIMARY KEY (`MaCTT`),
  INDEX `MaBCTC_idx` (`MaBCTC` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETTHU_BAOCAOTHUCHI`
    FOREIGN KEY (`MaBCTC`)
    REFERENCES `database-qllk`.`BAOCAOTHUCHI` (`MaBCTC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETTHU_CHITIETHOADON`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`CHITIETHOADON` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETCHI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETCHI` (
  `MaCTC` int AUTO_INCREMENT NOT NULL,
  `MaBCTC` int NULL,
  `MaMH` int NULL,
  `TongNhap` INT NULL,
  PRIMARY KEY (`MaCTC`),
  INDEX `MaBCTC_idx` (`MaBCTC` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETCHI_BAOCAOTHUCHI`
    FOREIGN KEY (`MaBCTC`)
    REFERENCES `database-qllk`.`BAOCAOTHUCHI` (`MaBCTC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETCHI_CHITIETPHIEUNHAP`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`CHITIETPHIEUNHAP` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM `database-qllk`.khachhang;
insert into `database-qllk`.khachhang values (NULL, N'Đặng Hoàng Long', N'123 Đường ABC', N'long97@gmail.com', '0123456789');
insert into `database-qllk`.khachhang values (NULL, N'Phạm Nhật Phi', N'3 Đường số 2', N'phipn@gmail.com', '0903123456');
insert into `database-qllk`.khachhang values (NULL, N'Trần Minh Hoàng Long', N'357 Đường DEF', N'test@gmail.com', '0909154782');

SELECT * FROM `database-qllk`.phongban;
insert into `database-qllk`.PHONGBAN values (NULL, N'Bộ phận kế toán');
insert into `database-qllk`.PHONGBAN values (NULL, N'Bộ phận kinh doanh');
insert into `database-qllk`.PHONGBAN values (NULL, N'Bộ phận thủ kho');
INSERT INTO `database-qllk`.PHONGBAN VALUES (NULL, N'Ban Giám đốc');

SELECT * FROM `database-qllk`.nhanvien;
insert into `database-qllk`.NHANVIEN values (NULL, N'Trần Văn A', N'Nam', '1');
insert into `database-qllk`.NHANVIEN values (NULL, N'Phạm Thị Minh', N'Nữ', '2');
insert into `database-qllk`.NHANVIEN values (NULL, N'Đặng Văn Thành', N'Nam', '4');
insert into `database-qllk`.NHANVIEN values (NULL, N'Nguyễn Thị Trang', N'Nữ', '3');

SELECT * FROM `database-qllk`.NHACUNGCAP;
DELETE FROM `database-qllk`.NHACUNGCAP WHERE MaNCC = 'NCC06';
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH Tin học Đông Phúc', N'147 ĐƯỜNG BA CU', 'DONGPHUC@GMAIL.COM', '0978456812');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH Nam Thông Bảo', N'258 ĐƯỜNG LÊ DUẨN', 'NAMTHONGBAO@GMAIL.COM', '0903456200');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH TM DV Tin Học Hoàng Khang', N'369 ĐƯỜNG HOA SỮA', 'HOANGKHANG@GMAIL.COM', '09039994533');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH TM & DV Nhật Tân Tín', N'357 ĐƯỜNG VÕ THỊ SÁU', 'NHATTANTIN@GMAIL.COM', '01228041103');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH MTV Tên Lửa Số', N'159 ĐƯỜNG ĐINH TIÊN HOÀNG', 'TENLUASO@GMAIL.COM', '01227456666');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES(NULL, N'Công Ty TNHH Vi Tính Tiến Phát', N'123 ĐƯỜNG LÊ VĂN SỈ', 'TIENPHAT@GMAIL.COM', '01697542311');

SELECT * FROM `database-qllk`.PHANQUYEN;
insert into `database-qllk`.PHANQUYEN values (NULL, N'Admin');
insert into `database-qllk`.PHANQUYEN values (NULL, N'Kế Toán');
insert into `database-qllk`.PHANQUYEN values (NULL, N'Kinh doanh');
insert into `database-qllk`.PHANQUYEN values (NULL, N'Thủ kho');
	
SELECT * FROM `database-qllk`.DANGNHAP;
INSERT INTO `database-qllk`.DANGNHAP VALUES (NULL, N'Bộ phận kế toán', 'ketoan', '123', '2', '2');
INSERT INTO `database-qllk`.DANGNHAP VALUES (NULL, N'Bộ phận kinh doanh', 'kinhdoanh', '123', '5', '3');
INSERT INTO `database-qllk`.DANGNHAP VALUES (NULL, N'Bộ phận thủ kho', 'thukho', '123', '4', '4');
INSERT INTO `database-qllk`.DANGNHAP VALUES (NULL, N'ADMIN Giám đốc', 'admin', '123', '3', '1');

SELECT * FROM `database-qllk`.DONVITINH;
INSERT INTO `database-qllk`.DONVITINH VALUES ('1', N'CÁI');
INSERT INTO `database-qllk`.DONVITINH VALUES ('2', N'CÂY');
INSERT INTO `database-qllk`.DONVITINH VALUES ('3', N'BỘ');

SELECT * FROM `database-qllk`.KHO;
INSERT INTO `database-qllk`.KHO VALUES ('1', N'A');
INSERT INTO `database-qllk`.KHO VALUES ('2', N'B');
INSERT INTO `database-qllk`.KHO VALUES ('3', N'C');

SELECT * FROM `database-qllk`.LOAIMATHANG;
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('1', N'RAM MÁY TÍNH');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('2', N'CARD ĐỒ HỌA');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('3', N'MÀN HÌNH MÁY TÍNH');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('4', N'BÀN PHÍM MÁY TÍNH');

SELECT * FROM `database-qllk`.MATHANG; 
SELECT * FROM `database-qllk`.MATHANG WHERE TenMH = "KEYBOARD";
INSERT INTO `database-qllk`.MATHANG VALUES ('1', N'KEYBOARD', N'LOGITECH', '1', 'KEYBOARD MÀU ĐEN CƠ NẶNG 30g', '4', '2', '20');
INSERT INTO `database-qllk`.MATHANG VALUES ('2', N'KEYBOARD APPLE', N'APPLE', '1', 'KEYBOARD MÀU TRẮNG', '4', '2', '15');
INSERT INTO `database-qllk`.MATHANG VALUES ('3', N'RAM 2016', N'INTEL', '2', 'RAM 32GB', '1', '1', '25');

SELECT * FROM `database-qllk`.BAOCAOHANGTON;
INSERT INTO `database-qllk`.BAOCAOHANGTON VALUES (null, '2018/06/11', '6', '0', '0', '0', '3');

SELECT * FROM `database-qllk`.CHITIETBAOCAOHANGTON;
INSERT INTO `database-qllk`.CHITIETBAOCAOHANGTON VALUES (NULL, '40', '10', '30', '4','2');
INSERT INTO `database-qllk`.CHITIETBAOCAOHANGTON VALUES (NULL, '60', '25', '35', '2','2');
delete from `database-qllk`.BAOCAOHANGTON where MaBCHT = 'BCHT001';

SELECT BCHT.MaBCHT, BCHT.NgayLap, BCHT.Thang, NV.TenNV, SUM(CTBC.LuongNhapBĐ) AS TongNhap, SUM(CTBC.LuongBan) AS TongBan, SUM(CTBC.LuongTon) AS TongTon FROM BAOCAOHANGTON BCHT JOIN NHANVIEN NV ON BCHT.MaNV = NV.MaNV AND CTBC.MaBCHT = BCHT.MaBCHT;

delete from `database-qllk`.CHITIETBAOCAOHANGTON where MaCTBC = '1';
SELECT CTBCHT.MaCTBC, MH.TenMH, SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETBAOCAOHANGTON CTBCHT JOIN MATHANG MH JOIN CHITIETPHIEUNHAP CTPN JOIN CHITIETHOADON CTHD 
ON CTBCHT.MaMH = MH.MaMH AND CTPN.MaMH = CTBCHT.MaMH AND CTHD.MaMH = CTBCHT.MaMH 
WHERE MaBCHT = '1' 
GROUP BY TenMH;
SELECT BCHT.MaBCHT, SUM(CTBC.LuongNhapBĐ) AS TongNhap, SUM(CTBC.LuongTon) AS TongTon, SUM(CTBC.LuongBan) AS TongBan FROM BAOCAOHANGTON BCHT JOIN CHITIETBAOCAOHANGTON CTBC ON CTBC.MaBCHT = BCHT.MaBCHT WHERE BCHT.Thang = '6';

SELECT MH.MaMH, MH.TenMH, MONTH(HD.NgayLap) AS Thang, SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN, HOADON HD, CHITIETHOADON CTHD, MATHANG MH 
WHERE CTPN.MaPN = PN.MaPN AND CTHD.MaHD = HD.MaHD AND CTHD.MaMH = MH.MaMH 
AND MONTH(PN.NgayLapPhieu) = '6' AND MONTH(HD.NgayLap) = '6' GROUP BY MH.TenMH;

SELECT CTPN.MaMH, MONTH(PN.NgayLapPhieu) AS Thang, SUM(CTPN.SoLuong) AS LuongNhapBĐ
FROM CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN
WHERE CTPN.MaPN = PN.MaPN
AND MONTH(PN.NgayLapPhieu) = '6' GROUP BY CTPN.MaMH;

SELECT CTHD.MaMH, MONTH(HD.NgayLap) AS Thang, SUM(CTHD.SoLuong) AS LuongBan
FROM HOADON HD, CHITIETHOADON CTHD
WHERE CTHD.MaHD = HD.MaHD
AND MONTH(HD.NgayLap) = '6' GROUP BY CTHD.MaMH;

SELECT * FROM MATHANG;

SELECT * FROM HOADON HD where MONTH(HD.NgayLap) = '6';

SELECT * FROM `database-qllk`.CHITIETBAOCAOHANGTON;

select * from hoadon where MONTH(NgayLap) = '6';
SELECT CTBCHT.MaCTBC, SUM(CTPN.SoLuong) AS LuongNhap, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon, MH.MaMH, BCHT.MaBCHT 
FROM BAOCAOHANGTON BCHT, CHITIETBAOCAOHANGTON CTBCHT, CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN, HOADON HD, CHITIETHOADON CTHD, MATHANG MH 
WHERE CTBCHT.MaBCHT = BCHT.MaBCHT AND CTBCHT.MaMH = MH.MaMH AND CTPN.MaPN = PN.MaPN AND CTHD.MaHD = HD.MaHD AND CTHD.MaMH = MH.MaMH
AND MONTH(PN.NgayLapPhieu) = '6' AND MONTH(HD.NgayLap) = '6' 
GROUP BY MH.TenMH; 	

SELECT MH.TenMH, MONTH(HD.NgayLap), SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN, HOADON HD, CHITIETHOADON CTHD, MATHANG MH 
WHERE CTPN.MaPN = PN.MaPN AND CTHD.MaHD = HD.MaHD AND CTHD.MaMH = MH.MaMH 
AND MONTH(PN.NgayLapPhieu) = '" + month + "' AND MONTH(HD.NgayLap) = '" + month + "' GROUP BY MH.TenMH;

SELECT * FROM `database-qllk`.BAOCAOTHUCHI;

SELECT * FROM `database-qllk`.DONDATHANG;
INSERT INTO `database-qllk`.DONDATHANG VALUES (NULL, '2018/05/30', '2', '1');
INSERT INTO `database-qllk`.DONDATHANG VALUES (NULL, '2018/06/10', '4', '5');
INSERT INTO `database-qllk`.DONDATHANG VALUES (NULL, '2018/05/25', '5', '2');
INSERT INTO `database-qllk`.DONDATHANG VALUES (NULL, '2018/06/05', '3', '3');

SELECT * FROM `database-qllk`.CHITIETDONDATHANG;
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES (NULL, '15', '1', '2');
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES (NULL, '20', '1', '1');
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES (NULL, '25', '3', '3');

SELECT SUM(CTHD.SoLuong) AS SoLuong FROM CHITIETHOADON CTHD WHERE CTHD.MaMH = '1' AND CTHD.MaHD = '1';
SELECT * FROM `database-qllk`.HOADON;
INSERT INTO `database-qllk`.HOADON VALUES (NULL, '2018/06/10', '1223165161', '', '2', '1');
UPDATE `database-qllk`.HOADON SET TongTien = '825000' WHere MaHD = '1'; 
SELECT HD.MaHD, HD.NgayLap, HD.MaSoThue, HD.TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH ON HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;
SELECT HD.MaHD, HD.NgayLap, HD.MaSoThue, HD.TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD AND HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;

SELECT * FROM `database-qllk`.CHITIETHOADON;
INSERT INTO `database-qllk`.CHITIETHOADON VALUES (NULL, '165000', '5', '1', '3', '825000');
SELECT HD.MaHD, NgayLap, MaSoThue, SUM(NULLIF(CTHD.TienThanhToan, 1)) AS TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD AND HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;
SELECT HD.MaHD, NVL(SUM(CTHD.TienThanhToan),0) AS TongTien FROM HOADON HD LEFT JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD;

SELECT * FROM CHITIETBAOCAOHANGTON CTBC WHERE CTBC.MaMH IN (SELECT MH.MaMH, MH.TenMH, MONTH(HD.NgayLap) AS Thang, SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN, HOADON HD, CHITIETHOADON CTHD, MATHANG MH 
WHERE CTPN.MaPN = PN.MaPN AND CTHD.MaHD = HD.MaHD AND CTHD.MaMH = MH.MaMH 
AND MONTH(PN.NgayLapPhieu) = '6' AND MONTH(HD.NgayLap) = '6' GROUP BY MH.TenMH);

SELECT * FROM `database-qllk`.PHIEUNHAPHANG;
INSERT INTO `database-qllk`.PHIEUNHAPHANG VALUES (NULL, '2018/06/01', '3', '37500000', '3');
INSERT INTO `database-qllk`.PHIEUNHAPHANG VALUES (NULL, '2018/06/05', '5', '7500000', '1');

SELECT * FROM `database-qllk`.CHITIETPHIEUNHAP;
SELECT SUM(CTPN.SoLuong) FROM CHITIETPHIEUNHAP CTPN where CTPN.MaPN = '5';

INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES (NULL, '20', '150000', '180000', N'ĐÃ NHẬP ĐỦ', '2', '3000000', '1');
INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES (NULL, '15', '300000', '350000', N'ĐÃ NHẬP ĐỦ', '2', '4500000', '4');
INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES (NULL, '25', '1500000', '1800000', N'ĐÃ NHẬP ĐỦ', '2', '37500000', '3');